version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: docanalyzer
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    environment:
      - GEMINI_API_KEY=AIzaSyA1cOEN9YHS5XEn8PcZXbKPc3ghGw0qPeg
      - DATABASE_URL=postgresql://user:password@postgres:5432/docanalyzer
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  postgres_data:
